# Generated by Django 4.2.7 on 2023-11-30 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Task name')),
                ('description', models.CharField(max_length=500, verbose_name='Task description')),
                ('due_date', models.DateTimeField(verbose_name='Due date')),
                ('is_completed', models.BooleanField(verbose_name='Is completed')),
            ],
        ),
    ]
